/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalheConoscoRouteImport } from './routes/trabalhe-conosco'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'

const TrabalheConoscoRoute = TrabalheConoscoRouteImport.update({
  id: '/trabalhe-conosco',
  path: '/trabalhe-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/login'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/trabalhe-conosco'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/login'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/trabalhe-conosco'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/login'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/trabalhe-conosco'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  NovidadesRoute: typeof NovidadesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TrabalheConoscoRoute: typeof TrabalheConoscoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhe-conosco': {
      id: '/trabalhe-conosco'
      path: '/trabalhe-conosco'
      fullPath: '/trabalhe-conosco'
      preLoaderRoute: typeof TrabalheConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  NovidadesRoute: NovidadesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SobreRoute: SobreRoute,
  TrabalheConoscoRoute: TrabalheConoscoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
