/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalheConoscoRouteImport } from './routes/trabalhe-conosco'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as NossasHistoriasRouteImport } from './routes/nossas-historias'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FichasRouteImport } from './routes/fichas'
import { Route as DoeRouteImport } from './routes/doe'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NossasHistoriasIndexRouteImport } from './routes/nossas-historias.index'
import { Route as FichasIndexRouteImport } from './routes/fichas.index'
import { Route as NossasHistoriasBookRouteImport } from './routes/nossas-historias.$book'
import { Route as FichasSheetIdRouteImport } from './routes/fichas.$sheetId'

const TrabalheConoscoRoute = TrabalheConoscoRouteImport.update({
  id: '/trabalhe-conosco',
  path: '/trabalhe-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const NossasHistoriasRoute = NossasHistoriasRouteImport.update({
  id: '/nossas-historias',
  path: '/nossas-historias',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FichasRoute = FichasRouteImport.update({
  id: '/fichas',
  path: '/fichas',
  getParentRoute: () => rootRouteImport,
} as any)
const DoeRoute = DoeRouteImport.update({
  id: '/doe',
  path: '/doe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NossasHistoriasIndexRoute = NossasHistoriasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NossasHistoriasRoute,
} as any)
const FichasIndexRoute = FichasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FichasRoute,
} as any)
const NossasHistoriasBookRoute = NossasHistoriasBookRouteImport.update({
  id: '/$book',
  path: '/$book',
  getParentRoute: () => NossasHistoriasRoute,
} as any)
const FichasSheetIdRoute = FichasSheetIdRouteImport.update({
  id: '/$sheetId',
  path: '/$sheetId',
  getParentRoute: () => FichasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/doe': typeof DoeRoute
  '/fichas': typeof FichasRouteWithChildren
  '/login': typeof LoginRoute
  '/nossas-historias': typeof NossasHistoriasRouteWithChildren
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/fichas/$sheetId': typeof FichasSheetIdRoute
  '/nossas-historias/$book': typeof NossasHistoriasBookRoute
  '/fichas/': typeof FichasIndexRoute
  '/nossas-historias/': typeof NossasHistoriasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/doe': typeof DoeRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/fichas/$sheetId': typeof FichasSheetIdRoute
  '/nossas-historias/$book': typeof NossasHistoriasBookRoute
  '/fichas': typeof FichasIndexRoute
  '/nossas-historias': typeof NossasHistoriasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/doe': typeof DoeRoute
  '/fichas': typeof FichasRouteWithChildren
  '/login': typeof LoginRoute
  '/nossas-historias': typeof NossasHistoriasRouteWithChildren
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/fichas/$sheetId': typeof FichasSheetIdRoute
  '/nossas-historias/$book': typeof NossasHistoriasBookRoute
  '/fichas/': typeof FichasIndexRoute
  '/nossas-historias/': typeof NossasHistoriasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/conta'
    | '/contato'
    | '/doe'
    | '/fichas'
    | '/login'
    | '/nossas-historias'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/trabalhe-conosco'
    | '/fichas/$sheetId'
    | '/nossas-historias/$book'
    | '/fichas/'
    | '/nossas-historias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/conta'
    | '/contato'
    | '/doe'
    | '/login'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/trabalhe-conosco'
    | '/fichas/$sheetId'
    | '/nossas-historias/$book'
    | '/fichas'
    | '/nossas-historias'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/conta'
    | '/contato'
    | '/doe'
    | '/fichas'
    | '/login'
    | '/nossas-historias'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/trabalhe-conosco'
    | '/fichas/$sheetId'
    | '/nossas-historias/$book'
    | '/fichas/'
    | '/nossas-historias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContaRoute: typeof ContaRoute
  ContatoRoute: typeof ContatoRoute
  DoeRoute: typeof DoeRoute
  FichasRoute: typeof FichasRouteWithChildren
  LoginRoute: typeof LoginRoute
  NossasHistoriasRoute: typeof NossasHistoriasRouteWithChildren
  NovidadesRoute: typeof NovidadesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TrabalheConoscoRoute: typeof TrabalheConoscoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhe-conosco': {
      id: '/trabalhe-conosco'
      path: '/trabalhe-conosco'
      fullPath: '/trabalhe-conosco'
      preLoaderRoute: typeof TrabalheConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossas-historias': {
      id: '/nossas-historias'
      path: '/nossas-historias'
      fullPath: '/nossas-historias'
      preLoaderRoute: typeof NossasHistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichas': {
      id: '/fichas'
      path: '/fichas'
      fullPath: '/fichas'
      preLoaderRoute: typeof FichasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doe': {
      id: '/doe'
      path: '/doe'
      fullPath: '/doe'
      preLoaderRoute: typeof DoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossas-historias/': {
      id: '/nossas-historias/'
      path: '/'
      fullPath: '/nossas-historias/'
      preLoaderRoute: typeof NossasHistoriasIndexRouteImport
      parentRoute: typeof NossasHistoriasRoute
    }
    '/fichas/': {
      id: '/fichas/'
      path: '/'
      fullPath: '/fichas/'
      preLoaderRoute: typeof FichasIndexRouteImport
      parentRoute: typeof FichasRoute
    }
    '/nossas-historias/$book': {
      id: '/nossas-historias/$book'
      path: '/$book'
      fullPath: '/nossas-historias/$book'
      preLoaderRoute: typeof NossasHistoriasBookRouteImport
      parentRoute: typeof NossasHistoriasRoute
    }
    '/fichas/$sheetId': {
      id: '/fichas/$sheetId'
      path: '/$sheetId'
      fullPath: '/fichas/$sheetId'
      preLoaderRoute: typeof FichasSheetIdRouteImport
      parentRoute: typeof FichasRoute
    }
  }
}

interface FichasRouteChildren {
  FichasSheetIdRoute: typeof FichasSheetIdRoute
  FichasIndexRoute: typeof FichasIndexRoute
}

const FichasRouteChildren: FichasRouteChildren = {
  FichasSheetIdRoute: FichasSheetIdRoute,
  FichasIndexRoute: FichasIndexRoute,
}

const FichasRouteWithChildren =
  FichasRoute._addFileChildren(FichasRouteChildren)

interface NossasHistoriasRouteChildren {
  NossasHistoriasBookRoute: typeof NossasHistoriasBookRoute
  NossasHistoriasIndexRoute: typeof NossasHistoriasIndexRoute
}

const NossasHistoriasRouteChildren: NossasHistoriasRouteChildren = {
  NossasHistoriasBookRoute: NossasHistoriasBookRoute,
  NossasHistoriasIndexRoute: NossasHistoriasIndexRoute,
}

const NossasHistoriasRouteWithChildren = NossasHistoriasRoute._addFileChildren(
  NossasHistoriasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContaRoute: ContaRoute,
  ContatoRoute: ContatoRoute,
  DoeRoute: DoeRoute,
  FichasRoute: FichasRouteWithChildren,
  LoginRoute: LoginRoute,
  NossasHistoriasRoute: NossasHistoriasRouteWithChildren,
  NovidadesRoute: NovidadesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SobreRoute: SobreRoute,
  TrabalheConoscoRoute: TrabalheConoscoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
