/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalheConoscoRouteImport } from './routes/trabalhe-conosco'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoeRouteImport } from './routes/doe'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NossasHistoriasIndexRouteImport } from './routes/nossas-historias.index'
import { Route as NossasHistoriasBookRouteImport } from './routes/nossas-historias.$book'

const TrabalheConoscoRoute = TrabalheConoscoRouteImport.update({
  id: '/trabalhe-conosco',
  path: '/trabalhe-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoeRoute = DoeRouteImport.update({
  id: '/doe',
  path: '/doe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NossasHistoriasIndexRoute = NossasHistoriasIndexRouteImport.update({
  id: '/nossas-historias/',
  path: '/nossas-historias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NossasHistoriasBookRoute = NossasHistoriasBookRouteImport.update({
  id: '/$book',
  path: '/$book',
  getParentRoute: () => NossasHistoriasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/doe': typeof DoeRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/nossas-historias/$book': typeof NossasHistoriasBookRoute
  '/nossas-historias/': typeof NossasHistoriasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/doe': typeof DoeRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/nossas-historias/$book': typeof NossasHistoriasBookRoute
  '/nossas-historias': typeof NossasHistoriasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/doe': typeof DoeRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/nossas-historias/$book': typeof NossasHistoriasBookRoute
  '/nossas-historias/': typeof NossasHistoriasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/conta'
    | '/contato'
    | '/doe'
    | '/login'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/trabalhe-conosco'
    | '/nossas-historias/$book'
    | '/nossas-historias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/conta'
    | '/contato'
    | '/doe'
    | '/login'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/trabalhe-conosco'
    | '/nossas-historias/$book'
    | '/nossas-historias'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/conta'
    | '/contato'
    | '/doe'
    | '/login'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/trabalhe-conosco'
    | '/nossas-historias/$book'
    | '/nossas-historias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContaRoute: typeof ContaRoute
  ContatoRoute: typeof ContatoRoute
  DoeRoute: typeof DoeRoute
  LoginRoute: typeof LoginRoute
  NovidadesRoute: typeof NovidadesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TrabalheConoscoRoute: typeof TrabalheConoscoRoute
  NossasHistoriasIndexRoute: typeof NossasHistoriasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhe-conosco': {
      id: '/trabalhe-conosco'
      path: '/trabalhe-conosco'
      fullPath: '/trabalhe-conosco'
      preLoaderRoute: typeof TrabalheConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doe': {
      id: '/doe'
      path: '/doe'
      fullPath: '/doe'
      preLoaderRoute: typeof DoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossas-historias/': {
      id: '/nossas-historias/'
      path: '/nossas-historias'
      fullPath: '/nossas-historias/'
      preLoaderRoute: typeof NossasHistoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossas-historias/$book': {
      id: '/nossas-historias/$book'
      path: '/$book'
      fullPath: '/nossas-historias/$book'
      preLoaderRoute: typeof NossasHistoriasBookRouteImport
      parentRoute: typeof NossasHistoriasRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContaRoute: ContaRoute,
  ContatoRoute: ContatoRoute,
  DoeRoute: DoeRoute,
  LoginRoute: LoginRoute,
  NovidadesRoute: NovidadesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SobreRoute: SobreRoute,
  TrabalheConoscoRoute: TrabalheConoscoRoute,
  NossasHistoriasIndexRoute: NossasHistoriasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
